//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradersMarketplace.ApplicationDbServiceClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DbContext", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Entity")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TradersMarketplace.ApplicationDbServiceClient.IdentityDbContextOfApplicationUserIdentityRolestringIdentityUserLoginIdentityUserRoleIdentityUserClaimBSeew7sY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TradersMarketplace.ApplicationDbServiceClient.IdentityDbContextOfApplicationUseropwjd3rz))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TradersMarketplace.ApplicationDbServiceClient.ApplicationDbContext))]
    public partial class DbContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdentityDbContextOfApplicationUserIdentityRolestringIdentityUserLoginIdentityUser" +
        "RoleIdentityUserClaimBSeew7sY", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.AspNet.Identity.EntityFramework" +
        "")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TradersMarketplace.ApplicationDbServiceClient.IdentityDbContextOfApplicationUseropwjd3rz))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TradersMarketplace.ApplicationDbServiceClient.ApplicationDbContext))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TradersMarketplace.ApplicationDbServiceClient.DbContext))]
    public partial class IdentityDbContextOfApplicationUserIdentityRolestringIdentityUserLoginIdentityUserRoleIdentityUserClaimBSeew7sY : TradersMarketplace.ApplicationDbServiceClient.DbContext {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RequireUniqueEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object RolesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object UsersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RequireUniqueEmail {
            get {
                return this.RequireUniqueEmailField;
            }
            set {
                if ((this.RequireUniqueEmailField.Equals(value) != true)) {
                    this.RequireUniqueEmailField = value;
                    this.RaisePropertyChanged("RequireUniqueEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Roles {
            get {
                return this.RolesField;
            }
            set {
                if ((object.ReferenceEquals(this.RolesField, value) != true)) {
                    this.RolesField = value;
                    this.RaisePropertyChanged("Roles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdentityDbContextOfApplicationUseropwjd3rz", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.AspNet.Identity.EntityFramework" +
        "")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TradersMarketplace.ApplicationDbServiceClient.ApplicationDbContext))]
    public partial class IdentityDbContextOfApplicationUseropwjd3rz : TradersMarketplace.ApplicationDbServiceClient.IdentityDbContextOfApplicationUserIdentityRolestringIdentityUserLoginIdentityUserRoleIdentityUserClaimBSeew7sY {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationDbContext", Namespace="http://schemas.datacontract.org/2004/07/DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class ApplicationDbContext : TradersMarketplace.ApplicationDbServiceClient.IdentityDbContextOfApplicationUseropwjd3rz {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ApplicationDbServiceClient.IApplicationDbContextService")]
    public interface IApplicationDbContextService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationDbContextService/Create", ReplyAction="http://tempuri.org/IApplicationDbContextService/CreateResponse")]
        TradersMarketplace.ApplicationDbServiceClient.ApplicationDbContext Create();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationDbContextService/Create", ReplyAction="http://tempuri.org/IApplicationDbContextService/CreateResponse")]
        System.Threading.Tasks.Task<TradersMarketplace.ApplicationDbServiceClient.ApplicationDbContext> CreateAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IApplicationDbContextServiceChannel : TradersMarketplace.ApplicationDbServiceClient.IApplicationDbContextService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApplicationDbContextServiceClient : System.ServiceModel.ClientBase<TradersMarketplace.ApplicationDbServiceClient.IApplicationDbContextService>, TradersMarketplace.ApplicationDbServiceClient.IApplicationDbContextService {
        
        public ApplicationDbContextServiceClient() {
        }
        
        public ApplicationDbContextServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApplicationDbContextServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationDbContextServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationDbContextServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TradersMarketplace.ApplicationDbServiceClient.ApplicationDbContext Create() {
            return base.Channel.Create();
        }
        
        public System.Threading.Tasks.Task<TradersMarketplace.ApplicationDbServiceClient.ApplicationDbContext> CreateAsync() {
            return base.Channel.CreateAsync();
        }
    }
}
