//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradersMarketplace.MenusServiceClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenusView", Namespace="http://schemas.datacontract.org/2004/07/Common.Views")]
    [System.SerializableAttribute()]
    public partial class MenusView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasSubmenusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MenuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.IEnumerable<Common.Views.MenusView> SubmenusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Action {
            get {
                return this.ActionField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionField, value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasSubmenus {
            get {
                return this.HasSubmenusField;
            }
            set {
                if ((this.HasSubmenusField.Equals(value) != true)) {
                    this.HasSubmenusField = value;
                    this.RaisePropertyChanged("HasSubmenus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MenuId {
            get {
                return this.MenuIdField;
            }
            set {
                if ((this.MenuIdField.Equals(value) != true)) {
                    this.MenuIdField = value;
                    this.RaisePropertyChanged("MenuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Position {
            get {
                return this.PositionField;
            }
            set {
                if ((this.PositionField.Equals(value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.IEnumerable<Common.Views.MenusView> Submenus {
            get {
                return this.SubmenusField;
            }
            set {
                if ((object.ReferenceEquals(this.SubmenusField, value) != true)) {
                    this.SubmenusField = value;
                    this.RaisePropertyChanged("Submenus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MenusServiceClient.IMenusService")]
    public interface IMenusService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenusService/GetGuestMenus", ReplyAction="http://tempuri.org/IMenusService/GetGuestMenusResponse")]
        System.Collections.Generic.IEnumerable<Common.Views.MenusView> GetGuestMenus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenusService/GetGuestMenus", ReplyAction="http://tempuri.org/IMenusService/GetGuestMenusResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<Common.Views.MenusView>> GetGuestMenusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenusService/GetUserMenus", ReplyAction="http://tempuri.org/IMenusService/GetUserMenusResponse")]
        System.Collections.Generic.IEnumerable<Common.Views.MenusView> GetUserMenus(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenusService/GetUserMenus", ReplyAction="http://tempuri.org/IMenusService/GetUserMenusResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<Common.Views.MenusView>> GetUserMenusAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMenusServiceChannel : TradersMarketplace.MenusServiceClient.IMenusService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MenusServiceClient : System.ServiceModel.ClientBase<TradersMarketplace.MenusServiceClient.IMenusService>, TradersMarketplace.MenusServiceClient.IMenusService {
        
        public MenusServiceClient() {
        }
        
        public MenusServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MenusServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MenusServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MenusServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.IEnumerable<Common.Views.MenusView> GetGuestMenus() {
            return base.Channel.GetGuestMenus();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<Common.Views.MenusView>> GetGuestMenusAsync() {
            return base.Channel.GetGuestMenusAsync();
        }
        
        public System.Collections.Generic.IEnumerable<Common.Views.MenusView> GetUserMenus(string username) {
            return base.Channel.GetUserMenus(username);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<Common.Views.MenusView>> GetUserMenusAsync(string username) {
            return base.Channel.GetUserMenusAsync(username);
        }
    }
}
