//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradersMarketplace.OrdersServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrdersServiceClient.IOrdersService")]
    public interface IOrdersService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersService/PlaceOrder", ReplyAction="http://tempuri.org/IOrdersService/PlaceOrderResponse")]
        void PlaceOrder(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersService/PlaceOrder", ReplyAction="http://tempuri.org/IOrdersService/PlaceOrderResponse")]
        System.Threading.Tasks.Task PlaceOrderAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersService/UpdateOrderStatus", ReplyAction="http://tempuri.org/IOrdersService/UpdateOrderStatusResponse")]
        void UpdateOrderStatus(System.Guid id, int statusId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdersService/UpdateOrderStatus", ReplyAction="http://tempuri.org/IOrdersService/UpdateOrderStatusResponse")]
        System.Threading.Tasks.Task UpdateOrderStatusAsync(System.Guid id, int statusId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrdersServiceChannel : TradersMarketplace.OrdersServiceClient.IOrdersService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdersServiceClient : System.ServiceModel.ClientBase<TradersMarketplace.OrdersServiceClient.IOrdersService>, TradersMarketplace.OrdersServiceClient.IOrdersService {
        
        public OrdersServiceClient() {
        }
        
        public OrdersServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdersServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void PlaceOrder(string username) {
            base.Channel.PlaceOrder(username);
        }
        
        public System.Threading.Tasks.Task PlaceOrderAsync(string username) {
            return base.Channel.PlaceOrderAsync(username);
        }
        
        public void UpdateOrderStatus(System.Guid id, int statusId) {
            base.Channel.UpdateOrderStatus(id, statusId);
        }
        
        public System.Threading.Tasks.Task UpdateOrderStatusAsync(System.Guid id, int statusId) {
            return base.Channel.UpdateOrderStatusAsync(id, statusId);
        }
    }
}
