//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradersMarketplace.UsersServiceClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserView", Namespace="http://schemas.datacontract.org/2004/07/Common.Views")]
    [System.SerializableAttribute()]
    public partial class UserView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfirmPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Common.Views.CreditCardDetailView> CreditCardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IbanNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RequiresDeliveryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResidenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Common.Views.RoleView> UserRolesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Web.Mvc.SelectList UserRolesListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConfirmPassword {
            get {
                return this.ConfirmPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfirmPasswordField, value) != true)) {
                    this.ConfirmPasswordField = value;
                    this.RaisePropertyChanged("ConfirmPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactNumber {
            get {
                return this.ContactNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNumberField, value) != true)) {
                    this.ContactNumberField = value;
                    this.RaisePropertyChanged("ContactNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Common.Views.CreditCardDetailView> CreditCards {
            get {
                return this.CreditCardsField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditCardsField, value) != true)) {
                    this.CreditCardsField = value;
                    this.RaisePropertyChanged("CreditCards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IbanNumber {
            get {
                return this.IbanNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IbanNumberField, value) != true)) {
                    this.IbanNumberField = value;
                    this.RaisePropertyChanged("IbanNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostCode {
            get {
                return this.PostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostCodeField, value) != true)) {
                    this.PostCodeField = value;
                    this.RaisePropertyChanged("PostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RequiresDelivery {
            get {
                return this.RequiresDeliveryField;
            }
            set {
                if ((this.RequiresDeliveryField.Equals(value) != true)) {
                    this.RequiresDeliveryField = value;
                    this.RaisePropertyChanged("RequiresDelivery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Residence {
            get {
                return this.ResidenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ResidenceField, value) != true)) {
                    this.ResidenceField = value;
                    this.RaisePropertyChanged("Residence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Town {
            get {
                return this.TownField;
            }
            set {
                if ((object.ReferenceEquals(this.TownField, value) != true)) {
                    this.TownField = value;
                    this.RaisePropertyChanged("Town");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Common.Views.RoleView> UserRoles {
            get {
                return this.UserRolesField;
            }
            set {
                if ((object.ReferenceEquals(this.UserRolesField, value) != true)) {
                    this.UserRolesField = value;
                    this.RaisePropertyChanged("UserRoles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Web.Mvc.SelectList UserRolesList {
            get {
                return this.UserRolesListField;
            }
            set {
                if ((object.ReferenceEquals(this.UserRolesListField, value) != true)) {
                    this.UserRolesListField = value;
                    this.RaisePropertyChanged("UserRolesList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditCardDetailView", Namespace="http://schemas.datacontract.org/2004/07/Common.Views")]
    [System.SerializableAttribute()]
    public partial class CreditCardDetailView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardHolderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditCardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditCardTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreditCardTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Web.Mvc.SelectList CreditCardTypeListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Web.Mvc.SelectList MonthsListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Web.Mvc.SelectList YearsListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardHolderName {
            get {
                return this.CardHolderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CardHolderNameField, value) != true)) {
                    this.CardHolderNameField = value;
                    this.RaisePropertyChanged("CardHolderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreditCardNumber {
            get {
                return this.CreditCardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditCardNumberField, value) != true)) {
                    this.CreditCardNumberField = value;
                    this.RaisePropertyChanged("CreditCardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreditCardType {
            get {
                return this.CreditCardTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditCardTypeField, value) != true)) {
                    this.CreditCardTypeField = value;
                    this.RaisePropertyChanged("CreditCardType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreditCardTypeId {
            get {
                return this.CreditCardTypeIdField;
            }
            set {
                if ((this.CreditCardTypeIdField.Equals(value) != true)) {
                    this.CreditCardTypeIdField = value;
                    this.RaisePropertyChanged("CreditCardTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Web.Mvc.SelectList CreditCardTypeList {
            get {
                return this.CreditCardTypeListField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditCardTypeListField, value) != true)) {
                    this.CreditCardTypeListField = value;
                    this.RaisePropertyChanged("CreditCardTypeList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpiryDate {
            get {
                return this.ExpiryDateField;
            }
            set {
                if ((this.ExpiryDateField.Equals(value) != true)) {
                    this.ExpiryDateField = value;
                    this.RaisePropertyChanged("ExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Month {
            get {
                return this.MonthField;
            }
            set {
                if ((this.MonthField.Equals(value) != true)) {
                    this.MonthField = value;
                    this.RaisePropertyChanged("Month");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Web.Mvc.SelectList MonthsList {
            get {
                return this.MonthsListField;
            }
            set {
                if ((object.ReferenceEquals(this.MonthsListField, value) != true)) {
                    this.MonthsListField = value;
                    this.RaisePropertyChanged("MonthsList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Web.Mvc.SelectList YearsList {
            get {
                return this.YearsListField;
            }
            set {
                if ((object.ReferenceEquals(this.YearsListField, value) != true)) {
                    this.YearsListField = value;
                    this.RaisePropertyChanged("YearsList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleView", Namespace="http://schemas.datacontract.org/2004/07/Common.Views")]
    [System.SerializableAttribute()]
    public partial class RoleView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleIdField, value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SelectListItem", Namespace="http://schemas.datacontract.org/2004/07/System.Web.Mvc")]
    [System.SerializableAttribute()]
    public partial class SelectListItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SelectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Selected {
            get {
                return this.SelectedField;
            }
            set {
                if ((this.SelectedField.Equals(value) != true)) {
                    this.SelectedField = value;
                    this.RaisePropertyChanged("Selected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsersServiceClient.IUsersService")]
    public interface IUsersService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/RegisterBuyer", ReplyAction="http://tempuri.org/IUsersService/RegisterBuyerResponse")]
        void RegisterBuyer(string id, string name, string surname, string residence, string street, string town, string postCode, string country, string contactNumber, int creditCardTypeId, string creditCardNumber, string cardHolderName, int expiryDateMonth, int expiryDateYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/RegisterBuyer", ReplyAction="http://tempuri.org/IUsersService/RegisterBuyerResponse")]
        System.Threading.Tasks.Task RegisterBuyerAsync(string id, string name, string surname, string residence, string street, string town, string postCode, string country, string contactNumber, int creditCardTypeId, string creditCardNumber, string cardHolderName, int expiryDateMonth, int expiryDateYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/RegisterSeller", ReplyAction="http://tempuri.org/IUsersService/RegisterSellerResponse")]
        void RegisterSeller(string id, string name, string surname, string residence, string street, string town, string postCode, string country, string contactNumber, bool requiresDelivery, string ibanNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/RegisterSeller", ReplyAction="http://tempuri.org/IUsersService/RegisterSellerResponse")]
        System.Threading.Tasks.Task RegisterSellerAsync(string id, string name, string surname, string residence, string street, string town, string postCode, string country, string contactNumber, bool requiresDelivery, string ibanNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/GetUser", ReplyAction="http://tempuri.org/IUsersService/GetUserResponse")]
        Common.Views.UserView GetUser(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/GetUser", ReplyAction="http://tempuri.org/IUsersService/GetUserResponse")]
        System.Threading.Tasks.Task<Common.Views.UserView> GetUserAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/GetUserForCheckout", ReplyAction="http://tempuri.org/IUsersService/GetUserForCheckoutResponse")]
        Common.Views.UserView GetUserForCheckout(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/GetUserForCheckout", ReplyAction="http://tempuri.org/IUsersService/GetUserForCheckoutResponse")]
        System.Threading.Tasks.Task<Common.Views.UserView> GetUserForCheckoutAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/GetAllUsers", ReplyAction="http://tempuri.org/IUsersService/GetAllUsersResponse")]
        System.Collections.Generic.List<Common.Views.UserView> GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/GetAllUsers", ReplyAction="http://tempuri.org/IUsersService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Common.Views.UserView>> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/AddUser", ReplyAction="http://tempuri.org/IUsersService/AddUserResponse")]
        void AddUser(string username, string password, string email, string name, string surname, string residence, string street, string town, string postCode, string country, string contactNumber, System.Collections.Generic.List<Common.Views.CreditCardDetailView> creditCards, bool requiresDelivery, string ibanNumber, System.Collections.Generic.List<Common.Views.RoleView> userRoles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/AddUser", ReplyAction="http://tempuri.org/IUsersService/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(string username, string password, string email, string name, string surname, string residence, string street, string town, string postCode, string country, string contactNumber, System.Collections.Generic.List<Common.Views.CreditCardDetailView> creditCards, bool requiresDelivery, string ibanNumber, System.Collections.Generic.List<Common.Views.RoleView> userRoles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/UpdateUser", ReplyAction="http://tempuri.org/IUsersService/UpdateUserResponse")]
        void UpdateUser(string id, string email, string name, string surname, string residence, string street, string town, string postCode, string country, string contactNumber, System.Collections.Generic.List<Common.Views.CreditCardDetailView> creditCards, bool requiresDelivery, string ibanNumber, System.Collections.Generic.List<Common.Views.RoleView> userRoles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/UpdateUser", ReplyAction="http://tempuri.org/IUsersService/UpdateUserResponse")]
        System.Threading.Tasks.Task UpdateUserAsync(string id, string email, string name, string surname, string residence, string street, string town, string postCode, string country, string contactNumber, System.Collections.Generic.List<Common.Views.CreditCardDetailView> creditCards, bool requiresDelivery, string ibanNumber, System.Collections.Generic.List<Common.Views.RoleView> userRoles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/UpdateUserPartial", ReplyAction="http://tempuri.org/IUsersService/UpdateUserPartialResponse")]
        void UpdateUserPartial(string username, string email, string residence, string street, string town, string postCode, string country, string contactNumber, System.Collections.Generic.List<Common.Views.CreditCardDetailView> creditCards);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/UpdateUserPartial", ReplyAction="http://tempuri.org/IUsersService/UpdateUserPartialResponse")]
        System.Threading.Tasks.Task UpdateUserPartialAsync(string username, string email, string residence, string street, string town, string postCode, string country, string contactNumber, System.Collections.Generic.List<Common.Views.CreditCardDetailView> creditCards);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/DeleteUser", ReplyAction="http://tempuri.org/IUsersService/DeleteUserResponse")]
        void DeleteUser(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/DeleteUser", ReplyAction="http://tempuri.org/IUsersService/DeleteUserResponse")]
        System.Threading.Tasks.Task DeleteUserAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsersServiceChannel : TradersMarketplace.UsersServiceClient.IUsersService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsersServiceClient : System.ServiceModel.ClientBase<TradersMarketplace.UsersServiceClient.IUsersService>, TradersMarketplace.UsersServiceClient.IUsersService {
        
        public UsersServiceClient() {
        }
        
        public UsersServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsersServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RegisterBuyer(string id, string name, string surname, string residence, string street, string town, string postCode, string country, string contactNumber, int creditCardTypeId, string creditCardNumber, string cardHolderName, int expiryDateMonth, int expiryDateYear) {
            base.Channel.RegisterBuyer(id, name, surname, residence, street, town, postCode, country, contactNumber, creditCardTypeId, creditCardNumber, cardHolderName, expiryDateMonth, expiryDateYear);
        }
        
        public System.Threading.Tasks.Task RegisterBuyerAsync(string id, string name, string surname, string residence, string street, string town, string postCode, string country, string contactNumber, int creditCardTypeId, string creditCardNumber, string cardHolderName, int expiryDateMonth, int expiryDateYear) {
            return base.Channel.RegisterBuyerAsync(id, name, surname, residence, street, town, postCode, country, contactNumber, creditCardTypeId, creditCardNumber, cardHolderName, expiryDateMonth, expiryDateYear);
        }
        
        public void RegisterSeller(string id, string name, string surname, string residence, string street, string town, string postCode, string country, string contactNumber, bool requiresDelivery, string ibanNumber) {
            base.Channel.RegisterSeller(id, name, surname, residence, street, town, postCode, country, contactNumber, requiresDelivery, ibanNumber);
        }
        
        public System.Threading.Tasks.Task RegisterSellerAsync(string id, string name, string surname, string residence, string street, string town, string postCode, string country, string contactNumber, bool requiresDelivery, string ibanNumber) {
            return base.Channel.RegisterSellerAsync(id, name, surname, residence, street, town, postCode, country, contactNumber, requiresDelivery, ibanNumber);
        }
        
        public Common.Views.UserView GetUser(string id) {
            return base.Channel.GetUser(id);
        }
        
        public System.Threading.Tasks.Task<Common.Views.UserView> GetUserAsync(string id) {
            return base.Channel.GetUserAsync(id);
        }
        
        public Common.Views.UserView GetUserForCheckout(string id) {
            return base.Channel.GetUserForCheckout(id);
        }
        
        public System.Threading.Tasks.Task<Common.Views.UserView> GetUserForCheckoutAsync(string id) {
            return base.Channel.GetUserForCheckoutAsync(id);
        }
        
        public System.Collections.Generic.List<Common.Views.UserView> GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Common.Views.UserView>> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public void AddUser(string username, string password, string email, string name, string surname, string residence, string street, string town, string postCode, string country, string contactNumber, System.Collections.Generic.List<Common.Views.CreditCardDetailView> creditCards, bool requiresDelivery, string ibanNumber, System.Collections.Generic.List<Common.Views.RoleView> userRoles) {
            base.Channel.AddUser(username, password, email, name, surname, residence, street, town, postCode, country, contactNumber, creditCards, requiresDelivery, ibanNumber, userRoles);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(string username, string password, string email, string name, string surname, string residence, string street, string town, string postCode, string country, string contactNumber, System.Collections.Generic.List<Common.Views.CreditCardDetailView> creditCards, bool requiresDelivery, string ibanNumber, System.Collections.Generic.List<Common.Views.RoleView> userRoles) {
            return base.Channel.AddUserAsync(username, password, email, name, surname, residence, street, town, postCode, country, contactNumber, creditCards, requiresDelivery, ibanNumber, userRoles);
        }
        
        public void UpdateUser(string id, string email, string name, string surname, string residence, string street, string town, string postCode, string country, string contactNumber, System.Collections.Generic.List<Common.Views.CreditCardDetailView> creditCards, bool requiresDelivery, string ibanNumber, System.Collections.Generic.List<Common.Views.RoleView> userRoles) {
            base.Channel.UpdateUser(id, email, name, surname, residence, street, town, postCode, country, contactNumber, creditCards, requiresDelivery, ibanNumber, userRoles);
        }
        
        public System.Threading.Tasks.Task UpdateUserAsync(string id, string email, string name, string surname, string residence, string street, string town, string postCode, string country, string contactNumber, System.Collections.Generic.List<Common.Views.CreditCardDetailView> creditCards, bool requiresDelivery, string ibanNumber, System.Collections.Generic.List<Common.Views.RoleView> userRoles) {
            return base.Channel.UpdateUserAsync(id, email, name, surname, residence, street, town, postCode, country, contactNumber, creditCards, requiresDelivery, ibanNumber, userRoles);
        }
        
        public void UpdateUserPartial(string username, string email, string residence, string street, string town, string postCode, string country, string contactNumber, System.Collections.Generic.List<Common.Views.CreditCardDetailView> creditCards) {
            base.Channel.UpdateUserPartial(username, email, residence, street, town, postCode, country, contactNumber, creditCards);
        }
        
        public System.Threading.Tasks.Task UpdateUserPartialAsync(string username, string email, string residence, string street, string town, string postCode, string country, string contactNumber, System.Collections.Generic.List<Common.Views.CreditCardDetailView> creditCards) {
            return base.Channel.UpdateUserPartialAsync(username, email, residence, street, town, postCode, country, contactNumber, creditCards);
        }
        
        public void DeleteUser(string id) {
            base.Channel.DeleteUser(id);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(string id) {
            return base.Channel.DeleteUserAsync(id);
        }
    }
}
