//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationUser
    {
        public ApplicationUser()
        {
            this.IdentityUserClaims = new HashSet<IdentityUserClaim>();
            this.IdentityUserLogins = new HashSet<IdentityUserLogin>();
            this.IdentityUserRoles = new HashSet<IdentityUserRole>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ContactNumber { get; set; }
        public string Residence { get; set; }
        public string Street { get; set; }
        public string PostCode { get; set; }
        public string Town { get; set; }
        public string Country { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<IdentityUserClaim> IdentityUserClaims { get; set; }
        public virtual ICollection<IdentityUserLogin> IdentityUserLogins { get; set; }
        public virtual ICollection<IdentityUserRole> IdentityUserRoles { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
