//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCardDetail
    {
        public int Id { get; set; }
        public int CreditCardTypeId { get; set; }
        public string CardHolderName { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string Username { get; set; }
    
        public virtual CreditCardType CreditCardType { get; set; }
        public virtual User User { get; set; }
    }
}
