//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.Menus1 = new HashSet<Menu>();
            this.IdentityRoles = new HashSet<IdentityRole>();
        }
    
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public string Action { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
    
        public virtual ICollection<Menu> Menus1 { get; set; }
        public virtual Menu Menu1 { get; set; }
        public virtual ICollection<IdentityRole> IdentityRoles { get; set; }
    }
}
