//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCommission
    {
        public int ProductId { get; set; }
        public int CommissionTypeId { get; set; }
        public decimal Amount { get; set; }
    
        public virtual CommissionType CommissionType { get; set; }
        public virtual Product Product { get; set; }
    }
}
