//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public bool SettingsId { get; set; }
        public Nullable<decimal> VatRate { get; set; }
        public string SystemEmail { get; set; }
        public string SystemEmailPassword { get; set; }
        public Nullable<int> DefaultRole { get; set; }
        public Nullable<int> GuestRole { get; set; }
    }
}
