//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CreditCardDetails = new HashSet<CreditCardDetail>();
            this.Orders = new HashSet<Order>();
            this.ShoppingCarts = new HashSet<ShoppingCart>();
            this.Roles = new HashSet<Role>();
        }
    
        public string Username { get; set; }
        public byte[] Password { get; set; }
        public string Email { get; set; }
        public string ContactNumber { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Residence { get; set; }
        public string Street { get; set; }
        public string Town { get; set; }
        public string PostCode { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<CreditCardDetail> CreditCardDetails { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Seller Seller { get; set; }
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
